accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'signup'
urlpatterns = [
     #login
     #logout
     path('signup',signup_view, name='signup'),
     #signup

]

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog.views import *
app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single_view, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', search_view, name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap
sitemaps = {
    'static': StaticViewSitemap,
    'blog' : BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path
from website.views import *
app_name = 'website'
urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('elemntry', elemntry_view, name='elemntry'),
    path('newsletter', newsletter_view, name='newsletter')
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    content_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {}" .format(self.title, self.id)

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})

website/models.py
import email
from django.db import models

# Create your models here.
class Contact(models.Model):
     name = models.CharField(max_length=255)
     email = models.EmailField()
     subject = models.CharField(max_length=255,blank=True)
     message = models.TextField()
     created_at = models.DateTimeField(auto_now_add=True)
     update_at = models.DateTimeField(auto_now=True)
     class Meta:
          ordering = ['created_at']
     def __str__(self):
          return self.name

class NewsLetter(models.Model):
     email = models.EmailField()

     def __str__(self):
          return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=255)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

class LoginForm(AuthenticationForm):
    email = forms.EmailField(max_length=254)
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

website/forms.py
from django import forms
from website.models import Contact, NewsLetter
from captcha.fields import CaptchaField

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        fields = '__all__'
class NewsLetterForm(forms.ModelForm):

    class Meta:
        model = NewsLetter
        fields = '__all__'

accounts/views.py
import email
from multiprocessing import context
from urllib import request
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from accounts.forms import SignUpForm, LoginForm
# Create your views here.


def signup_view(request):
    if not request.user.is_authenticated:
        
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/')
        
        form = SignUpForm()
        context = {'form': form}
        return render(request, 'signup/signup.html', context)
    else:
        return redirect('/')

blog/views.py
from atexit import register
import datetime
from pickle import NONE
from django.shortcuts import render, get_object_or_404
from blog.models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def blog_view(response, cat_name=None, author_username=None, **kwargs):
    posts = Post.objects.filter(status=1)
    if author_username:
        posts = posts.filter(author__username=author_username)
    if cat_name:
        posts = posts.filter(category__name=cat_name)

    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    posts = Paginator(posts, 3)
    try:
        page_num = response.GET.get('page')
        posts = posts.get_page(page_num)
    except EmptyPage:
        posts = posts.get_page(1)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    context = {'posts': posts}
    return render(response, 'blog/blog-home.html', context)


def blog_single_view(response, pid):
    posts = Post.objects.filter(status=1)
    post = get_object_or_404(posts, pk=pid, status=1)
    post.content_view += 1
    post.save()
    nextpost = Post.objects.filter(id__gt=post.pk).order_by('pk').first()
    prevpost = Post.objects.filter(id__lt=post.pk).order_by('pk').last()
    context = {'post': post, 'nextpost': nextpost, 'prevpost': prevpost}

    return render(response, 'blog/blog-single.html', context)


def search_view(response):
    posts = Post.objects.filter(status=1)
    if response.method == 'GET':
        if s := response.GET.get('s'):
            posts = posts.filter(content__contains=s)
    context = {'posts': posts}
    return render(response, 'blog/blog-home.html', context)

website/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from website.forms import ContactForm, NewsLetterForm
from django.contrib import messages

def index_view(response):
    return render(response, 'website/index.html')


def about_view(response):
    return render(response, 'website/about.html')


def newsletter_view(response):
    if response.method == 'POST':
        form = NewsLetterForm(response.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

def contact_view(response):
    if response.method == 'POST':
        form = ContactForm(response.POST)
        if form.is_valid():
            fs= form.save(commit=False)
            fs.name= "uknown"
            fs.save()
            messages.add_message(response, messages.SUCCESS,'successfully!')
        else:
            messages.add_message(response, messages.ERROR,'your ticket didnt submited!')
    form = ContactForm()
    return render(response, 'website/contact.html')


def elemntry_view(response):
    return render(response, 'website/elements.html')

templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>login</title>

    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post" action="{% url 'accounts:login' %}">
     {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputEmail" class="sr-only">username</label>
      <input type="text" name="username" class="form-control" placeholder="username" required autofocus>
      
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password" class="form-control" placeholder="password" requiredPassword" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>

     <!-- Mobile Specific Meta -->
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <!-- Favicon-->
     <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
     <!-- Author Meta -->
     <meta name="author" content="colorlib">
     <!-- Meta Description -->
     <meta name="description" content="">
     <!-- Meta Keyword -->
     <meta name="keywords" content="">
     <!-- meta character set -->
     <meta charset="UTF-8">
     <!-- Site Title -->
     <title>Travel</title>

     <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
     <!--
          CSS
          ============================================= -->
     <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
     <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
     <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
     <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
     <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
     <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
     <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
     <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
     <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
     <header id="header">
          <div class="header-top">
               <div class="container">
                    <div class="row align-items-center">
                         <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                              <ul>
                                   {% if request.user.is_authenticated %}
                                   <li><a href="#">logged in as {{request.user.username}}</a></li>
                                   <li><a href="{% url 'logout' %}">logout</a></li>
                                   {% else %}
                                   <li><a href="{% url 'login' %}">Login</a></li>
                                   <li><a href="{% url 'signup:signup' %}">Signup</a></li>
                                   {% endif %}
                              </ul>
                         </div>
                         <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                              <div class="header-social">
                                   <a href="#"><i class="fa fa-facebook"></i></a>
                                   <a href="#"><i class="fa fa-twitter"></i></a>
                                   <a href="#"><i class="fa fa-dribbble"></i></a>
                                   <a href="#"><i class="fa fa-behance"></i></a>
                              </div>
                         </div>
                    </div>
               </div>
          </div>
          <div class="container main-menu">
               <div class="row align-items-center justify-content-between d-flex">
                    <div id="logo">
                         <a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt=""
                                   title="" /></a>
                    </div>
                    <nav id="nav-menu-container">
                         <ul class="nav-menu">
                              <li><a href="{% url 'website:index' %}">Home</a></li>
                              <li><a href="{% url 'website:about' %}">About</a></li>
                              <li><a href="{% url 'blog:index' %}">Blog</a></li>
                              </li>
                              <li class="menu-has-children"><a href="">Pages</a>
                                   <ul>
                                        <li><a href="{% url 'website:elemntry' %}">Elements</a></li>
                                        <li class="menu-has-children"><a href="">Level 2 </a>
                                             <ul>
                                                  <li><a href="#">Item One</a></li>
                                                  <li><a href="#">Item Two</a></li>
                                             </ul>
                                        </li>
                                   </ul>
                              </li>
                              <li><a href="{% url 'website:contact' %}">Contact</a></li>
                         </ul>
                    </nav><!-- #nav-menu-container -->
               </div>
          </div>

          {% if messages %}
          {% for message in messages %}
          <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} m-2" id="msg" role="alert">{{ message|safe }}</div>
          {% endfor %}
          {% endif %}
     </header><!-- #header -->
     {% block content %}

     {% endblock %}


     <!-- start footer Area -->
     <footer class="footer-area section-gap">
          <div class="container">

               <div class="row">
                    <div class="col-lg-3  col-md-6 col-sm-6">
                         <div class="single-footer-widget">
                              <h6>About Agency</h6>
                              <p>
                                   The world has become so fast paced that people don’t want to stand by reading a page
                                   of information, they would much rather look at a presentation and understand the
                                   message. It has come to a point
                              </p>
                         </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                         <div class="single-footer-widget">
                              <h6>Navigation Links</h6>
                              <div class="row">
                                   <div class="col">
                                        <ul>
                                             <li><a href="#">Home</a></li>
                                             <li><a href="#">Feature</a></li>
                                             <li><a href="#">Services</a></li>
                                             <li><a href="#">Portfolio</a></li>
                                        </ul>
                                   </div>
                                   <div class="col">
                                        <ul>
                                             <li><a href="#">Team</a></li>
                                             <li><a href="#">Pricing</a></li>
                                             <li><a href="#">Blog</a></li>
                                             <li><a href="#">Contact</a></li>
                                        </ul>
                                   </div>
                              </div>
                         </div>
                    </div>
                    <div class="col-lg-3  col-md-6 col-sm-6">
                         <div class="single-footer-widget">
                              <h6>Newsletter</h6>
                              <p>
                                   For business professionals caught between high OEM price and mediocre print and
                                   graphic output.
                              </p>
                              <div>
                                   <form action="{% url 'website:newsletter' %}" method="post"
                                        class="subscription relative">
                                        {% csrf_token %}
                                        <div class="input-group d-flex flex-row">
                                             <input name="email" placeholder="Email Address"
                                                  onfocus="this.placeholder = ''"
                                                  onblur="this.placeholder = 'Email Address '" required="" type="email">
                                             <button class="btn bb-btn" type="submit"><span
                                                       class="lnr lnr-location"></span></button>
                                        </div>
                                        <div class="mt-10 info"></div>
                                   </form>
                              </div>
                         </div>
                    </div>
                    <div class="col-lg-3  col-md-6 col-sm-6">
                         <div class="single-footer-widget mail-chimp">
                              <h6 class="mb-20">InstaFeed</h6>
                              <ul class="instafeed d-flex flex-wrap">
                                   <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                                   <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                                   <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                                   <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                                   <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                                   <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                                   <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                                   <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                              </ul>
                         </div>
                    </div>
               </div>

               <div class="row footer-bottom d-flex justify-content-between align-items-center">
                    <p class="col-lg-8 col-sm-12 footer-text m-0">
                         <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                         Copyright &copy;
                         <script>document.write(new Date().getFullYear());</script> All rights reserved | This template
                         is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                              target="_blank">Colorlib</a>
                         <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                    <div class="col-lg-4 col-sm-12 footer-social">
                         <a href="#"><i class="fa fa-facebook"></i></a>
                         <a href="#"><i class="fa fa-twitter"></i></a>
                         <a href="#"><i class="fa fa-dribbble"></i></a>
                         <a href="#"><i class="fa fa-behance"></i></a>
                    </div>

               </div>
          </div>
     </footer>
     <!-- End footer Area -->

     <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
     <script src="{% static 'js/popper.min.js' %}"></script>
     <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
     <script src="{% static 'js/jquery-ui.js' %}"></script>
     <script src="{% static 'js/easing.min.js' %}"></script>
     <script src="{% static 'js/hoverIntent.js' %}"></script>
     <script src="{% static 'js/superfish.min.js' %}"></script>
     <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
     <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
     <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
     <script src="{% static 'js/owl.carousel.min.js' %}"></script>
     <script src="{% static 'js/mail-script.js' %}"></script>
     <script src="{% static 'js/main.js' %}"></script>
     <script>
          setTimeout(function () {
               if ($('#msg').length > 0) {
                    $('#msg').remove();
               }
          }, 2000);
     </script>
</body>

</html>

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
     <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load blog_tags %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					a Telescope
				</h1>
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Social life</h4>
								<span></span>
								<p>Enjoy your social life together</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Politics</h4>
								<span></span>
								<p>Be a part of politics</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Food</h4>
								<span></span>
								<p>Let the food be finished</p>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				{% for post in posts %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a></li>
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></p> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_at|date:"d M Y"}}</a> <span
									class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.content_view}} Views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span
									class="lnr lnr-bubble"></span></p>
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.image.url}}" alt="">
						</div>
						<a class="posts-title" href="{% url 'blog:single' pid=post.id %}">
							<h3>{{post.title}}</h3>
						</a>
						<p class="excert">
						{{post.content|truncatewords:41 }}
						</p>
						<a href="blog-single.html" class="primary-btn">View More</a>
					</div>
				</div>
				{% endfor %}
				<nav class="blog-pagination justify-content-center d-flex">
					<ul class="pagination">
						{% if posts.has_previous %}
						<li class="page-item">
							<a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-left"></span>
								</span>
							</a>
						</li>
						{% endif %}
						{% for i in posts.paginator.page_range %}
						{% if posts.number == i %}
							<li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
							{% else %}
							<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
						{% endif %}
						
						{% endfor %}

						{% if posts.has_next %}
						<li class="page-item">
							<a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-right"></span>
								</span>
							</a>
						</li>
						{% endif %}
					</ul>
					
				</nav>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/blog-search.html'%}
					{% include 'blog/blog-writer.html'%}
					{% latestpost %}
					{% include 'blog/blog-ads.html'%}
					{% postcategories %}
					{% include 'blog/blog-newsletter.html'%}
					{% include 'blog/blog-tag-cloud.html'%}
					
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->
{% endblock %}

templates/blog/blog-popular-post.html
{% load static %}
{% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
     <h4 class="popular-title">Popular Posts</h4>
     <div class="popular-post-list">
          {% for post in posts %}
          <div class="single-post-list d-flex flex-row align-items-center">
               <div class="thumb">
                    <img class="img-fluid" src="{{post.image.url}}" alt="">
               </div>
               <div class="details">
                    <a href="{% url 'blog:single' pid=post.id %}">
                         <h6>{{post.title}}</h6>
                    </a>
                    <p>{{post.published_at|naturaltime}}</p>
               </div>
          </div>
          {% endfor %}
     </div>
</div>

templates/blog/blog-post-category.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
     <h4 class="category-title">Post Catgories</h4>
     <ul class="cat-list">
          {% for name,count in categories.items %}
          <li>
               <a href="{% url 'blog:category' cat_name=name%}" class="d-flex justify-content-between">
                    <p>{{name}}</p>
                    <p>{{count}}</p>
               </a>
          </li>
          {% endfor %}
     </ul>
</div>

templates/blog/blog-search.html
{% load static %}
<div class="single-sidebar-widget search-widget">
     <form class="search-form" action="{% url 'blog:search' %}" method="get">
          <input placeholder="Search Posts" name="s" type="text"
               onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
          <button type="submit"><i class="fa fa-search"></i></button>
     </form>
</div>

templates/blog/blog-tag-cloud.html
{% load static %}
<div class="single-sidebar-widget tag-cloud-widget">
     <h4 class="tagcloud-title">Tag Clouds</h4>
     <ul>
          {% for tag in post.tags.all %}
          <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
          {% endfor %}
     </ul>
</div>

templates/signup/signup.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>signup</title>

    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post" action="{% url 'signup:signup' %}">
     {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">sign UP</h1>
      <label for="inputEmail" class="sr-only">username</label>
      <input type="text" name="username" class="form-control" placeholder="username" required autofocus>
      <input type="email" name="email" class="form-control" placeholder="email" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password1" class="form-control" placeholder="password" requiredPassword" required>
      <input type="password" name="password2" class="form-control" placeholder="confirm password" requiredPassword" required>
      <div class="checkbox mb-3">
        <label>
          
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>